### PR TITLE
Fixed the Player Issue

### PR DESCRIPTION
**Pull request by athul**
Sir while you merge this PR just `squash and merge` it. That way only one commit will be set. Change the Player URL and everything will be alright😄

### CODE REVIEW

**Comment by athul** [comment]
Or You can just copy the `<video>` element from the Player's Source Code which you can see at the `Inspect Element` option.

But that would be tedious work and you'll have to make specific pages for it

**Comment by nidhin84** [comment]
In audio player It's ok. I need a download button on that page. How can I fix it?

**Comment by nidhin84** [comment]
Can i have  gh-pages for private repo???

**Comment by athul** [comment]
> Can i have gh-pages for private repo???

No SIr, Thats for PRO version of GitHub

**Pull request merged**
